ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS logo_url TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS primary_color TEXT DEFAULT '#1a1a1a',
  ADD COLUMN IF NOT EXISTS welcome_message TEXT DEFAULT NULL;
